sudo: required
language: generic
services:
  - docker

before_installed:
  - docker build -t 10001024/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 10001024/react-test npm test

after_success:
  - docker build -t 10001024/multi_client ./client
  - docker build -t 10001024/multi_nginx ./nginx
  - docker build -t 10001024/multi_server ./server
  - docker build -t 10001024/multi_worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 10001024/multi_client
  - docker push 10001024/multi_nginx
  - docker push 10001024/multi_server
  - docker push 10001024/multi_worker
